"""Generate a lightweight, presentation-ready HTML page from the real data pipeline.

The page explains the variables, shows key plots, and summarizes the regression
result so you can present the pipeline without live coding. It produces a
single self-contained HTML file (Plotly + MathJax are loaded via CDN) that you
can open locally or host statically.

Usage examples (after installing dependencies from requirements.txt):
    python scripts/presentation_app.py --output build/presentation.html --open
    python scripts/presentation_app.py --output docs/index.html
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path
from textwrap import dedent

import pandas as pd
import plotly.express as px
import plotly.io as pio

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.append(str(SCRIPT_DIR))
from pull_and_model import load_raw, run_model, tidy_panel  # noqa: E402


def _make_figures(panel: pd.DataFrame):
    """Return Plotly HTML snippets for line and scatter views."""
    longest_countries = (
        panel.groupby("country").size().sort_values(ascending=False).head(5).index.tolist()
    )
    line_subset = panel[panel["country"].isin(longest_countries)]
    line_fig = px.line(
        line_subset,
        x="year",
        y="homicide_rate_per_100k",
        color="country",
        markers=True,
        title="Homicide rate per 100k over time (top data-rich countries)",
    )

    scatter_fig = px.scatter(
        panel,
        x="gini_worldbank",
        y="homicide_rate_per_100k",
        color="country",
        trendline="ols",
        labels={
            "gini_worldbank": "Inequality (Gini, World Bank)",
            "homicide_rate_per_100k": "Homicide rate per 100k",
        },
        title="Inequality vs. homicide (with OLS trendline)",
    )

    return {
        "line": pio.to_html(line_fig, include_plotlyjs=False, full_html=False),
        "scatter": pio.to_html(scatter_fig, include_plotlyjs=False, full_html=False),
    }


def _build_html(fig_html: dict[str, str], model_summary: str) -> str:
    """Assemble the presentation HTML."""
    today = date.today().isoformat()
    return dedent(
        rf"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <title>Crime & Inequality: Data-First Pipeline</title>
          <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
          <style>
            body {{ font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #0d1117; color: #e6edf3; }}
            header {{ background: linear-gradient(120deg, #4f46e5, #9333ea); padding: 32px; color: white; }}
            h1, h2, h3 {{ margin: 0 0 12px; }}
            main {{ padding: 24px; max-width: 1100px; margin: 0 auto; }}
            section {{ margin-bottom: 32px; background: #161b22; padding: 20px; border-radius: 12px; border: 1px solid #30363d; box-shadow: 0 10px 30px rgba(0,0,0,0.25); }}
            code, pre {{ background: #0b1021; color: #c9d1d9; padding: 4px 6px; border-radius: 6px; }}
            .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; }}
            .pill {{ display: inline-block; padding: 6px 12px; border-radius: 999px; background: #1f6feb; color: white; font-weight: 600; margin-right: 6px; }}
            a {{ color: #8ab4f8; }}
          </style>
        </head>
        <body>
          <header>
            <p class="pill">Data + Equations</p>
            <h1>Crime & Inequality: Real Data + Transparent Models</h1>
            <p>Autogenerated on {today}. Everything below comes from reproducible code in this repo.</p>
          </header>
          <main>
            <section>
              <h2>Data sources (official / public)</h2>
              <div class="grid">
                <div><strong>Homicide rate</strong><br/>Our World in Data (IHME, GBD 2019), per 100k people.</div>
                <div><strong>Inequality</strong><br/>World Bank Gini coefficients via OWID mirror.</div>
                <div><strong>Scope</strong><br/>Country-year panel with overlap between both series.</div>
              </div>
            </section>

            <section>
              <h2>Quick equations</h2>
              <p>We model homicide counts (C) with exposure (population N) using a log-link. Country (α_i) and year (γ_t) absorb unobserved differences:</p>
              <p>\[
              C_{{it}} \sim \text{{Poisson}}(\lambda_{{it}} N_{{it}}), \quad
              \log \lambda_{{it}} = \alpha_i + \gamma_t + \beta_G G_{{it}} + \mathbf{{X}}_{{it}}^\top \boldsymbol{{\delta}}
              \]</p>
              <p>Robust variance: \(\mathrm{{Var}}(\hat\beta) = (X^\top W X)^{{-1}} X^\top W \Sigma W X (X^\top W X)^{{-1}}\) with HC3 sandwich estimator.</p>
              <p>We also check dispersion-aware alternatives (NegBin2) and random effects:</p>
              <p>\[
                \log \lambda_{{it}} = \alpha + u_i + v_t + \beta_G G_{{it}} + \epsilon_{{it}}, \quad u_i \sim \mathcal N(0, \sigma_u^2)
              \]</p>
            </section>

            <section>
              <h2>Visual narrative</h2>
              <div>{fig_html['line']}</div>
              <div style="margin-top: 16px;">{fig_html['scatter']}</div>
            </section>

            <section>
              <h2>Model headline</h2>
              <p>We fit: \(\log Y_{{it}} = \alpha_i + \gamma_t + \beta_G G_{{it}} + \varepsilon_{{it}}\) where \(Y_{{it}}\) is homicide rate per 100k.</p>
              <pre>{model_summary}</pre>
              <p>The sign of \(\hat\beta_G\) tells whether higher inequality aligns with higher homicide within countries over time.</p>
            </section>

            <section>
              <h2>How to reproduce</h2>
              <ol>
                <li><code>pip install -r requirements.txt</code></li>
                <li><code>python scripts/pull_and_model.py --save-data data/owid_crime_panel.csv --summary</code></li>
                <li><code>python scripts/presentation_app.py --output build/presentation.html --open</code></li>
              </ol>
              <p>The generated HTML is static—share it or present offline.</p>
            </section>
          </main>
        </body>
        </html>
        """
    )


def build_presentation(cache_dir: Path, output: Path, open_file: bool = False):
    """Create the HTML presentation from the cached panel."""
    homicide, gini = load_raw(cache_dir)
    panel = tidy_panel(homicide, gini)
    model = run_model(panel)

    fig_html = _make_figures(panel)
    html = _build_html(fig_html, model.summary().as_text())

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html, encoding="utf-8")

    if open_file:
        import webbrowser

        webbrowser.open(output.resolve().as_uri())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-dir", type=Path, default=Path("data"), help="Where to cache downloaded CSVs.")
    parser.add_argument("--output", type=Path, default=Path("build/presentation.html"), help="Path for the HTML output.")
    parser.add_argument("--open", action="store_true", help="Open the generated HTML in the default browser.")
    args = parser.parse_args()

    build_presentation(args.cache_dir, args.output, open_file=args.open)


if __name__ == "__main__":
    main()
